from bika.lims import bikaMessageFactory as _
from bika.lims.browser.batchfolder import BatchFolderContentsView as BaseView


class BatchFolderContentsView(BaseView):
    """Override the default listing of batches.

    - Display additional review state filter buttons.
    - Additional columns available for display.
    """

    def __init__(self, context, request):
        super(BatchFolderContentsView, self).__init__(context, request)
        self.review_states = [
            {'id': 'active',
             'title': _('Active'),
             'columns': self.columns,
             'contentFilter': {'cancellation_state':'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'requested',
             'title': _('Requested'),
             'columns': self.columns,
             'contentFilter': {'review_state': 'requested',
                               'cancellation_review_state': 'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'approved',
             'title': _('Approved'),
             'columns': self.columns,
             'contentFilter': {'review_state': 'approved',
                               'cancellation_review_state': 'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'received',
             'title': _('Recieved'),
             'columns': self.columns,
             'contentFilter': {'review_state': 'received',
                               'cancellation_review_state': 'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'accepted',
             'title': _('Accepted'),
             'columns': self.columns,
             'contentFilter': {'review_state': 'accepted',
                               'cancellation_review_state': 'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'released',
             'title': _('Released'),
             'columns': self.columns,
             'contentFilter': {'review_state': 'released',
                               'cancellation_review_state': 'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'prepared',
             'title': _('Prepared'),
             'columns': self.columns,
             'contentFilter': {'review_state': 'prepared',
                               'cancellation_review_state': 'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'tested',
             'title': _('Tested'),
             'columns': self.columns,
             'contentFilter': {'review_state': 'tested',
                               'cancellation_review_state': 'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'passed_qa',
             'title': _('Passed QA'),
             'columns': self.columns,
             'contentFilter': {'review_state': 'passed_qa',
                               'cancellation_review_state': 'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'published',
             'title': _('Published'),
             'columns': self.columns,
             'contentFilter': {'review_state': 'published',
                               'cancellation_review_state': 'active',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'cancelled',
             'title': _('Cancelled'),
             'columns': self.columns,
             'contentFilter': {'cancellation_state': 'cancelled',
                               'sort_on': 'created',
                               'sort_order': 'reverse'}},
            {'id': 'all',
             'title': _('All'),
             'columns': self.columns,
             'contentFilter': {'sort_on': 'created',
                               'sort_order': 'reverse'}},
        ]
